USE dayacares;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS account_status ENUM('ACTIVE', 'BLOCKED') NOT NULL DEFAULT 'ACTIVE',
  ADD COLUMN IF NOT EXISTS max_daily_visits INT NOT NULL DEFAULT 8;

ALTER TABLE worker_allocations
  ADD COLUMN IF NOT EXISTS is_primary TINYINT(1) NOT NULL DEFAULT 0;

ALTER TABLE membership_invoices
  ADD COLUMN IF NOT EXISTS gst_rate INT NOT NULL DEFAULT 18,
  ADD COLUMN IF NOT EXISTS gst_inr INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS taxable_inr INT NOT NULL DEFAULT 0;

ALTER TABLE sos_incidents
  ADD COLUMN IF NOT EXISTS family_called_at DATETIME(3) NULL;
